# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify
# git push --no-verify
# test
#
# To update all hooks automatically:
#
# pre-commit autoupdate
fail_fast: false

default_language_version:
  python: python3.11.2

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch # prevent direct commits to the `main` branch
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # ruff version.
    rev: v0.11.12
    hooks:
      # Run the linter.
      #
      # When running with --fix, Ruff's lint hook should be placed before Ruff's formatter hook,
      # and before Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # typos
  - repo: https://github.com/crate-ci/typos
    rev: v1.33.1
    hooks:
      - id: typos
        exclude: |
          (?x)^(
            src/dispatch/database/revisions/core/versions/|
            src/dispatch/database/revisions/tenant/versions/|
            src/dispatch/static/dispatch/src/assets/icons/|
            data/dispatch-sample-data.dump|
            src/dispatch/plugins/dispatch_zoom/client.py
          )

  # pytest
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -v tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
