# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify
fail_fast: false

default_language_version:
  python: python3.11.2

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      #
      # When running with --fix, Ruff's lint hook should be placed before Ruff's formatter hook,
      # and before Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # Typos
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
      - id: typos

  # Pytest
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        stages: [push]
