// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/layouts/AdminLayout.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    AutoComplete: typeof import('./src/components/AutoComplete.vue')['default']
    BaseCombobox: typeof import('./src/components/BaseCombobox.vue')['default']
    BasicLayout: typeof import('./src/components/layouts/BasicLayout.vue')['default']
    ColorPickerInput: typeof import('./src/components/ColorPickerInput.vue')['default']
    DashboardLayout: typeof import('./src/components/layouts/DashboardLayout.vue')['default']
    DateChipGroupRelative: typeof import('./src/components/DateChipGroupRelative.vue')['default']
    DateTimePicker: typeof import('./src/components/DateTimePicker.vue')['default']
    DateTimePickerMenu: typeof import('./src/components/DateTimePickerMenu.vue')['default']
    DateWindowInput: typeof import('./src/components/DateWindowInput.vue')['default']
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    DMenu: typeof import('./src/components/DMenu.vue')['default']
    DTooltip: typeof import('./src/components/DTooltip.vue')['default']
    GenaiAnalysisDisplay: typeof import('./src/components/GenaiAnalysisDisplay.vue')['default']
    HtmlRenderer: typeof import('./src/components/HtmlRenderer.vue')['default']
    IconPickerInput: typeof import('./src/components/IconPickerInput.vue')['default']
    InfoWidget: typeof import('./src/components/InfoWidget.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LockButton: typeof import('./src/components/LockButton.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    NotificationSnackbarsWrapper: typeof import('./src/components/NotificationSnackbarsWrapper.vue')['default']
    ParticipantSelect: typeof import('./src/components/ParticipantSelect.vue')['default']
    PreciseDateTimePicker: typeof import('./src/components/PreciseDateTimePicker.vue')['default']
    Refresh: typeof import('./src/components/Refresh.vue')['default']
    RichEditor: typeof import('./src/components/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavingState: typeof import('./src/components/SavingState.vue')['default']
    SearchPopover: typeof import('./src/components/SearchPopover.vue')['default']
    SettingsBreadcrumbs: typeof import('./src/components/SettingsBreadcrumbs.vue')['default']
    StatWidget: typeof import('./src/components/StatWidget.vue')['default']
  }
}
