from fastapi import APIRouter

from dispatch.config import (
    DISPATCH_AUTHENTICATION_PROVIDER_SLUG,
    DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID,
    DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN,
    DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL,
    SENTRY_ENABLED,
    SENTRY_DSN,
)

router = APIRouter()


@router.get("")
def get_settings():
    """Retrieve all server settings."""
    return {
        "DISPATCH_AUTHENTICATION_PROVIDER_SLUG": DISPATCH_AUTHENTICATION_PROVIDER_SLUG,
        "DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID": DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID,
        "DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN": DISPATCH_AUTHENTICATION_PROVIDER_USE_ID_TOKEN,
        "DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL": DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL,
        "SENTRY_ENABLED": SENTRY_ENABLED,
        "SENTRY_DSN": SENTRY_DSN,
    }
