"""Adds incident role mappings

Revision ID: b73416df5744
Revises: 9fcf205ba6a5
Create Date: 2021-08-09 15:29:24.856985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b73416df5744"
down_revision = "9fcf205ba6a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("individual_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individual_contact.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_role_incident_priority",
        sa.Column("incident_role_id", sa.Integer(), nullable=False),
        sa.Column("incident_priority_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_priority_id"],
            ["incident_priority.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_role_id"],
            ["incident_role.id"],
        ),
        sa.PrimaryKeyConstraint("incident_role_id", "incident_priority_id"),
    )
    op.create_table(
        "incident_role_tag",
        sa.Column("incident_role_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_role_id"],
            ["incident_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("incident_role_id", "tag_id"),
    )
    op.create_table(
        "incident_role_incident_type",
        sa.Column("incident_role_id", sa.Integer(), nullable=False),
        sa.Column("incident_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_role_id"],
            ["incident_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_type_id"],
            ["incident_type.id"],
        ),
        sa.PrimaryKeyConstraint("incident_role_id", "incident_type_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incident_role_incident_type")
    op.drop_table("incident_role_tag")
    op.drop_table("incident_role_incident_priority")
    op.drop_table("incident_role")
    # ### end Alembic commands ###
