"""Adds missing feedback search_vector

Revision ID: 9fcf205ba6a5
Revises: b0b00d3e8330
Create Date: 2021-08-03 10:15:17.529189

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "9fcf205ba6a5"
down_revision = "b0b00d3e8330"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback",
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    )
    op.create_index(
        "feedback_search_vector_idx",
        "feedback",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("feedback_search_vector_idx", table_name="feedback", postgresql_using="gin")
    op.drop_column("feedback", "search_vector")
    # ### end Alembic commands ###
