"""Fixes typo in foreign key name

Revision ID: fe7343defaa6
Revises: 32811f581cb8
Create Date: 2021-07-09 11:29:10.038813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe7343defaa6"
down_revision = "32811f581cb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("incident_type_liason_service_id_fkey", "incident_type", type_="foreignkey")
    op.create_foreign_key(
        "incident_type_liaison_service_id_fkey",
        "incident_type",
        "service",
        ["liaison_service_id"],
        ["id"],
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    pass
