"""Adds ondelete cascade for report id foreign key

Revision ID: 2780d28e4f39
Revises: 875e6b212dc7
Create Date: 2021-07-22 14:59:14.822882

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "2780d28e4f39"
down_revision = "875e6b212dc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("document_report_id_fkey", "document", type_="foreignkey")
    op.create_foreign_key(None, "document", "report", ["report_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document", type_="foreignkey")
    op.create_foreign_key("document_report_id_fkey", "document", "report", ["report_id"], ["id"])
    # ### end Alembic commands ###
