"""empty message

Revision ID: 3820a792d88a
Revises: 3820fb661728
Create Date: 2021-09-16 16:33:40.605881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "3820a792d88a"
down_revision = "3820fb661728"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plugin_instance",
        sa.Column(
            "_configuration",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=True,
        ),
    )
    # op.drop_column("plugin_instance", "configuration")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plugin_instance",
        sa.Column("configuration", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    # op.drop_column("plugin_instance", "_configuration")
    # ### end Alembic commands ###
