"""Moving column name from plugin_id to plugin_instance_id

Revision ID: 32811f581cb8
Revises: c767b759a508
Create Date: 2021-06-23 10:45:12.839871

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "32811f581cb8"
down_revision = "c767b759a508"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("workflow_plugin_id_fkey", "workflow", type_="foreignkey")
    op.alter_column("workflow", "plugin_id", new_column_name="plugin_instance_id")
    op.create_foreign_key(None, "workflow", "plugin_instance", ["plugin_instance_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow", type_="foreignkey")
    op.alter_column("workflow", "plugin_instance_id", new_column_name="plugin_id")
    op.create_foreign_key(
        "workflow_plugin_id_fkey",
        "workflow",
        "plugin",
        ["plugin_id"],
        ["id"],
        referent_schema="dispatch_core",
    )
    # ### end Alembic commands ###
