"""Marks incident visibility as non-nullable

Revision ID: c767b759a508
Revises: 8a558baeef05
Create Date: 2021-06-18 16:12:17.723485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c767b759a508"
down_revision = "8a558baeef05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update incident set visibility = 'Open' where visibility is null;")
    op.alter_column("incident", "visibility", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("incident", "visibility", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
