"""Adds relationship to incident type in the case type data model

Revision ID: f9384b873721
Revises: 479024506e05
Create Date: 2022-09-02 13:54:20.742225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9384b873721"
down_revision = "479024506e05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case_type", sa.Column("incident_type_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "case_type", "incident_type", ["incident_type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "case_type", type_="foreignkey")
    op.drop_column("case_type", "incident_type_id")
    # ### end Alembic commands ###
