"""empty message

Revision ID: f0e0eada7276
Revises: d34e94f8d8bc
Create Date: 2022-10-25 15:57:00.303835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e0eada7276'
down_revision = 'd34e94f8d8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal', sa.Column('suppression_rule_id', sa.Integer(), nullable=True))
    op.drop_constraint('signal_supression_rule_id_fkey', 'signal', type_='foreignkey')
    op.create_foreign_key(None, 'signal', 'suppression_rule', ['suppression_rule_id'], ['id'])
    op.drop_column('signal', 'supression_rule_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal', sa.Column('supression_rule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'signal', type_='foreignkey')
    op.create_foreign_key('signal_supression_rule_id_fkey', 'signal', 'suppression_rule', ['supression_rule_id'], ['id'])
    op.drop_column('signal', 'suppression_rule_id')
    # ### end Alembic commands ###
