"""Adds a group relationship to the case data model

Revision ID: e003a33e2b81
Revises: 8d7232b7cbd4
Create Date: 2022-08-05 14:49:00.383167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e003a33e2b81"
down_revision = "8d7232b7cbd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("tactical_group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "case", "group", ["tactical_group_id"], ["id"])
    op.add_column("group", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "group", "case", ["case_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_column("group", "case_id")
    op.drop_constraint(None, "case", type_="foreignkey")
    op.drop_column("case", "tactical_group_id")
    # ### end Alembic commands ###
