"""Adds the ability to associate cases to workflow instances.

Revision ID: cfde1bca6a6e
Revises: e49209df586d
Create Date: 2022-09-23 11:36:09.154783

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cfde1bca6a6e"
down_revision = "e49209df586d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_instance", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "workflow_instance", "case", ["case_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow_instance", type_="foreignkey")
    op.drop_column("workflow_instance", "case_id")
    # ### end Alembic commands ###
