"""Adds a cascade for deleting cases."

Revision ID: eb348d46afd0
Revises: 34aeedc9d09a
Create Date: 2022-11-09 10:01:08.742441

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb348d46afd0"
down_revision = "34aeedc9d09a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("signal_instance_case_id_fkey", "signal_instance", type_="foreignkey")
    op.create_foreign_key(None, "signal_instance", "case", ["case_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "signal_instance", type_="foreignkey")
    op.create_foreign_key(
        "signal_instance_case_id_fkey", "signal_instance", "case", ["case_id"], ["id"]
    )
    # ### end Alembic commands ###
