"""empty message

Revision ID: d34e94f8d8bc
Revises: 534c316ba65b
Create Date: 2022-10-25 10:18:10.467883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34e94f8d8bc'
down_revision = '534c316ba65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('duplication_rule_signal_id_fkey', 'duplication_rule', type_='foreignkey')
    op.drop_column('duplication_rule', 'signal_id')
    op.add_column('signal', sa.Column('duplication_rule_id', sa.Integer(), nullable=True))
    op.add_column('signal', sa.Column('supression_rule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'signal', 'duplication_rule', ['duplication_rule_id'], ['id'])
    op.create_foreign_key(None, 'signal', 'suppression_rule', ['supression_rule_id'], ['id'])
    op.drop_constraint('suppression_rule_signal_id_fkey', 'suppression_rule', type_='foreignkey')
    op.drop_constraint('suppression_rule_creator_id_fkey', 'suppression_rule', type_='foreignkey')
    op.drop_column('suppression_rule', 'creator_id')
    op.drop_column('suppression_rule', 'signal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppression_rule', sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('suppression_rule', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('suppression_rule_creator_id_fkey', 'suppression_rule', 'dispatch_user', ['creator_id'], ['id'], referent_schema='dispatch_core')
    op.create_foreign_key('suppression_rule_signal_id_fkey', 'suppression_rule', 'signal', ['signal_id'], ['id'])
    op.drop_constraint(None, 'signal', type_='foreignkey')
    op.drop_constraint(None, 'signal', type_='foreignkey')
    op.drop_column('signal', 'supression_rule_id')
    op.drop_column('signal', 'duplication_rule_id')
    op.add_column('duplication_rule', sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('duplication_rule_signal_id_fkey', 'duplication_rule', 'signal', ['signal_id'], ['id'])
    # ### end Alembic commands ###
