"""empty message

Revision ID: 790a7da8f956
Revises: c2a7d394b56d
Create Date: 2022-02-25 13:30:50.151313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "790a7da8f956"
down_revision = "c2a7d394b56d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source", sa.Column("data_last_loaded_at", sa.DateTime(), nullable=True))
    op.drop_column("source", "last_refreshed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source",
        sa.Column("last_refreshed", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.drop_column("source", "data_last_loaded_at")
    # ### end Alembic commands ###
