"""Adds relationship between incident and incident severity

Revision ID: d6438d754467
Revises: 4f1af51dae6e
Create Date: 2022-10-17 13:16:05.234617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6438d754467"
down_revision = "4f1af51dae6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident", sa.Column("incident_severity_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "incident", "incident_severity", ["incident_severity_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incident", type_="foreignkey")
    op.drop_column("incident", "incident_severity_id")
    # ### end Alembic commands ###
