"""Adds column to case type table to support plugin metadata

Revision ID: 8d7232b7cbd4
Revises: cec9ab5c5c8e
Create Date: 2022-08-04 10:02:21.310067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d7232b7cbd4"
down_revision = "cec9ab5c5c8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case_type", sa.Column("plugin_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case_type", "plugin_metadata")
    # ### end Alembic commands ###
