"""Moves activity column to participant role model

Revision ID: 4b65941d065a
Revises: 3b0f5b81376f
Create Date: 2022-10-26 16:02:26.996119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b65941d065a"
down_revision = "3b0f5b81376f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant", "activity")
    op.add_column("participant_role", sa.Column("activity", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant_role", "activity")
    op.add_column(
        "participant", sa.Column("activity", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
