"""Adds case data model

Revision ID: 7b1511613b94
Revises: 5e2bc6083503
Create Date: 2022-06-21 15:10:19.657314

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "7b1511613b94"
down_revision = "5e2bc6083503"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("reported_at", sa.DateTime(), nullable=True),
        sa.Column("stable_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("reporter_id", sa.Integer(), nullable=True),
        sa.Column("duplicate_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["participant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_id"],
            ["case.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["participant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "case_search_vector_idx", "case", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "assoc_case_tags",
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["case.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("case_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assoc_case_tags")
    op.drop_index("case_search_vector_idx", table_name="case", postgresql_using="gin")
    op.drop_table("case")
    # ### end Alembic commands ###
