"""Adds resolution column to incident data model

Revision ID: 3097592c0739
Revises: 5f96c909a3c0
Create Date: 2022-02-15 15:48:45.724812

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3097592c0739"
down_revision = "5f96c909a3c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident", sa.Column("resolution", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident", "resolution")
    # ### end Alembic commands ###
