"""Adds support for related cases in the case data model

Revision ID: 33f35da7013b
Revises: 615ed0f95775
Create Date: 2022-08-10 13:27:05.121936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33f35da7013b"
down_revision = "615ed0f95775"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("related_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "case", "case", ["related_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "case", type_="foreignkey")
    op.drop_column("case", "related_id")
    # ### end Alembic commands ###
