"""Removes stable_at column and adds columns for triage_at and escalated_at timestamps"

Revision ID: 391f7c3e6992
Revises: 0785dceb3373
Create Date: 2022-08-01 12:43:22.577363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "391f7c3e6992"
down_revision = "0785dceb3373"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("triage_at", sa.DateTime(), nullable=True))
    op.add_column("case", sa.Column("escalated_at", sa.DateTime(), nullable=True))
    op.drop_column("case", "stable_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case", sa.Column("stable_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.drop_column("case", "escalated_at")
    op.drop_column("case", "triage_at")
    # ### end Alembic commands ###
