"""Adds cost to source data model.

Revision ID: c2a7d394b56d
Revises: b5d3706a1d54
Create Date: 2022-02-24 11:34:08.134713

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c2a7d394b56d"
down_revision = "b5d3706a1d54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source", sa.Column("cost", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "cost")
    # ### end Alembic commands ###
