"""Adds page_assignee column

Revision ID: bd61c1e1e7cd
Revises: f809d9e76ba3
Create Date: 2022-12-15 14:59:25.077450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd61c1e1e7cd"
down_revision = "f809d9e76ba3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case_priority", sa.Column("page_assignee", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case_priority", "page_assignee")
    # ### end Alembic commands ###
