"""Replaces composite primary key with a dedicated one

Revision ID: 86ec96cd14f8
Revises: a27964951d4f
Create Date: 2022-08-18 10:49:42.395466

"""
from alembic import op

# import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "86ec96cd14f8"
down_revision = "a27964951d4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("assoc_case_case_priority", sa.Column("id", sa.Integer(), nullable=False))
    op.drop_constraint("assoc_case_case_priority_pkey", "assoc_case_case_priority", type_="primary")
    op.execute("ALTER TABLE assoc_case_case_priority ADD COLUMN id SERIAL PRIMARY KEY")
    op.alter_column(
        "assoc_case_case_priority",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # op.add_column("assoc_case_case_severity", sa.Column("id", sa.Integer(), nullable=False))
    op.drop_constraint("assoc_case_case_severity_pkey", "assoc_case_case_severity", type_="primary")
    op.execute("ALTER TABLE assoc_case_case_severity ADD COLUMN id SERIAL PRIMARY KEY")
    op.alter_column(
        "assoc_case_case_severity",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # op.add_column("assoc_case_case_type", sa.Column("id", sa.Integer(), nullable=False))
    op.drop_constraint("assoc_case_case_type_pkey", "assoc_case_case_type", type_="primary")
    op.execute("ALTER TABLE assoc_case_case_type ADD COLUMN id SERIAL PRIMARY KEY")
    op.alter_column(
        "assoc_case_case_type", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assoc_case_case_type", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("assoc_case_case_type", "id")
    op.create_primary_key(
        "assoc_case_case_type_pkey", "assoc_case_case_type", ["case_id", "case_type_id"]
    )
    op.alter_column(
        "assoc_case_case_severity",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("assoc_case_case_severity", "id")
    op.create_primary_key(
        "assoc_case_case_severity_pkey", "assoc_case_case_severity", ["case_id", "case_severity_id"]
    )
    op.alter_column(
        "assoc_case_case_priority",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("assoc_case_case_priority", "id")
    op.create_primary_key(
        "assoc_case_case_priority_pkey", "assoc_case_case_priority", ["case_id", "case_priority_id"]
    )
    # ### end Alembic commands ###
