"""Adds support for documents in the case data model

Revision ID: 0344535782ee
Revises: a3d211ae5404
Create Date: 2022-08-09 11:15:24.353023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0344535782ee"
down_revision = "a3d211ae5404"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("case_document_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "case", "document", ["case_document_id"], ["id"])
    op.add_column("document", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "document", "case", ["case_id"], ["id"], ondelete="CASCADE", use_alter=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document", type_="foreignkey")
    op.drop_column("document", "case_id")
    op.drop_constraint(None, "case", type_="foreignkey")
    op.drop_column("case", "case_document_id")
    # ### end Alembic commands ###
