"""Adds support for storage in the case data model

Revision ID: a3d211ae5404
Revises: e003a33e2b81
Create Date: 2022-08-08 11:38:35.722076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3d211ae5404"
down_revision = "e003a33e2b81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("storage", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "storage", "case", ["case_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "storage", type_="foreignkey")
    op.drop_column("storage", "case_id")
    # ### end Alembic commands ###
