"""Removes relationship from task to ticket

Revision ID: c1abb0cc40e5
Revises: df200ca113f7
Create Date: 2022-09-30 10:26:15.849836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c1abb0cc40e5"
down_revision = "df200ca113f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_tickets")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_tickets",
        sa.Column("ticket_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="task_tickets_task_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["ticket.id"], name="task_tickets_ticket_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ticket_id", "task_id", name="task_tickets_pkey"),
    )
    # ### end Alembic commands ###
