"""Adds reminder delay time to Incident model

Revision ID: a3fb1380cf76
Revises: fa23324d5679
Create Date: 2023-07-05 14:27:32.239616

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a3fb1380cf76"
down_revision = "fa23324d5679"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident", sa.Column("delay_executive_report_reminder", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "incident", sa.Column("delay_tactical_report_reminder", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident", "delay_tactical_report_reminder")
    op.drop_column("incident", "delay_executive_report_reminder")
    # ### end Alembic commands ###
