"""Adds type to events

Revision ID: 3538650dc471
Revises: 0560fab4537f
Create Date: 2023-09-12 13:43:42.539336

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3538650dc471"
down_revision = "0560fab4537f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "type")
    # ### end Alembic commands ###
