"""Removes search vector from signal instance model

Revision ID: bdaeabba3e53
Revises: f2605bfc1f59
Create Date: 2023-11-29 12:59:45.408085

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "bdaeabba3e53"
down_revision = "f2605bfc1f59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "signal_instance_search_vector_idx", table_name="signal_instance", postgresql_using="gin"
    )
    op.drop_column("signal_instance", "search_vector")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
