"""Remove constraint

Revision ID: 35a2ad8b53a2
Revises: bad95cd82724
Create Date: 2023-06-05 16:02:46.337434

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "35a2ad8b53a2"
down_revision = "bad95cd82724"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("entity_type_name_project_id_key", "entity_type", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "entity_type_name_project_id_key", "entity_type", ["name", "project_id"]
    )
    # ### end Alembic commands ###
