"""empty message

Revision ID: e4b4991dddcd
Revises: 956eb8f8987e
Create Date: 2023-01-30 10:52:31.676368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e4b4991dddcd"
down_revision = "956eb8f8987e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("participants_team", sa.String(), nullable=True))
    op.add_column("case", sa.Column("participants_location", sa.String(), nullable=True))
    op.drop_constraint("case_assignee_id_fkey", "case", type_="foreignkey")
    # op.create_foreign_key(None, "case", "participant", ["assignee_id"], ["id"])
    op.add_column("participant", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "participant", "case", ["case_id"], ["id"], ondelete="CASCADE", use_alter=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.drop_column("participant", "case_id")
    op.drop_constraint(None, "case", type_="foreignkey")
    op.create_foreign_key(
        "case_assignee_id_fkey",
        "case",
        "dispatch_user",
        ["assignee_id"],
        ["id"],
        referent_schema="dispatch_core",
    )
    op.drop_column("case", "participants_location")
    op.drop_column("case", "participants_team")
    # ### end Alembic commands ###
