"""Adds new daily report settings

Revision ID: d6b8d02c1b86
Revises: a3fb1380cf76
Create Date: 2023-08-04 14:53:58.790499

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d6b8d02c1b86"
down_revision = "a3fb1380cf76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("send_daily_reports", sa.Boolean(), nullable=True),
        schema="dispatch_core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "send_daily_reports", schema="dispatch_core")
    # ### end Alembic commands ###
