"""Adds unique constraint in task model

Revision ID: 65db2acae3ea
Revises: 5955ed5f76b4
Create Date: 2023-03-02 11:16:27.810635

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "65db2acae3ea"
down_revision = "5955ed5f76b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "task", ["resource_id", "incident_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="unique")
    # ### end Alembic commands ###
