"""Allows many to many signal filters

Revision ID: 93b517de08e2
Revises: b168b50764c7
Create Date: 2023-02-13 15:19:36.921571

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "93b517de08e2"
down_revision = "b168b50764c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assoc_signal_filters",
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("signal_filter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["signal_filter_id"], ["signal_filter.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["signal_id"], ["signal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("signal_id", "signal_filter_id"),
    )
    op.drop_constraint("signal_filter_signal_id_fkey", "signal_filter", type_="foreignkey")
    op.drop_column("signal_filter", "signal_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signal_filter", sa.Column("signal_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "signal_filter_signal_id_fkey", "signal_filter", "signal", ["signal_id"], ["id"]
    )
    op.drop_table("assoc_signal_filters")
    # ### end Alembic commands ###
