"""Adds case override information to signal instances

Revision ID: 56eb1c0a3a92
Revises: 38a7fb709167
Create Date: 2023-04-20 12:42:17.734488

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "56eb1c0a3a92"
down_revision = "38a7fb709167"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signal_instance", sa.Column("case_type_id", sa.Integer(), nullable=True))
    op.add_column("signal_instance", sa.Column("case_priority_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "signal_instance", "case_priority", ["case_priority_id"], ["id"])
    op.create_foreign_key(None, "signal_instance", "case_type", ["case_type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "signal_instance", type_="foreignkey")
    op.drop_constraint(None, "signal_instance", type_="foreignkey")
    op.drop_column("signal_instance", "case_priority_id")
    op.drop_column("signal_instance", "case_type_id")
    # ### end Alembic commands ###
