"""Adds models for workstream types

Revision ID: 5483ae34742c
Revises: b48b245f9c4c
Create Date: 2023-03-22 11:04:10.311226

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "5483ae34742c"
down_revision = "b48b245f9c4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workstream_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.Column("document_template_id", sa.Integer(), nullable=True),
        sa.Column("oncall_service_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_template_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["oncall_service_id"],
            ["service.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "project_id"),
    )
    op.create_index(
        "workstream_type_search_vector_idx",
        "workstream_type",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "workstream_type_search_vector_idx", table_name="workstream_type", postgresql_using="gin"
    )
    op.drop_table("workstream_type")
    # ### end Alembic commands ###
