"""Adds project to the service feedback table and allows hours to be fractional

Revision ID: 064c71206256
Revises: 3538650dc471
Create Date: 2023-10-06 09:53:50.119947

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "064c71206256"
down_revision = "3538650dc471"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_feedback", sa.Column("project_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "service_feedback", "project", ["project_id"], ["id"])
    op.alter_column(
        "service_feedback", "hours", existing_type=sa.Integer(), type_=sa.Numeric(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service_feedback", type_="foreignkey")
    op.drop_column("service_feedback", "project_id")
    op.alter_column(
        "service_feedback", "hours", existing_type=sa.Numeric(), type_=sa.Integer(), nullable=True
    )
    # ### end Alembic commands ###
