"""Renames field column to jpath

Revision ID: 0a19c5a4c2ba
Revises: 35a2ad8b53a2
Create Date: 2023-06-06 08:54:24.986736

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a19c5a4c2ba"
down_revision = "35a2ad8b53a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("entity_type", "field", nullable=False, new_column_name="jpath")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("entity_type", "jpath", nullable=False, new_column_name="field")
    # ### end Alembic commands ###
