"""empty message

Revision ID: b48b245f9c4c
Revises: 7db13bf5c5d7
Create Date: 2023-03-14 16:56:11.844768

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b48b245f9c4c"
down_revision = "7db13bf5c5d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assoc_signal_workflows",
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["signal_id"], ["signal.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflow.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("signal_id", "workflow_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assoc_signal_workflows")
    # ### end Alembic commands ###
