"""Adds daily report setting to project

Revision ID: 6b98c28edd86
Revises: a3fb1380cf76
Create Date: 2023-08-04 17:36:18.646729

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6b98c28edd86"
down_revision = "a3fb1380cf76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("send_daily_reports", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "send_daily_reports")
    # ### end Alembic commands ###
