"""Adds service feedback data model

Revision ID: 4e57f5b1f3f3
Revises: 74d279f6e4f6
Create Date: 2023-04-04 09:43:04.586304

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "4e57f5b1f3f3"
down_revision = "74d279f6e4f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_feedback",
        sa.Column("rating", sa.String(), nullable=True),
        sa.Column("feedback", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hours", sa.Integer(), nullable=True),
        sa.Column("shift_start_at", sa.DateTime(), nullable=True),
        sa.Column("shift_end_at", sa.DateTime(), nullable=True),
        sa.Column("schedule", sa.String(), nullable=True),
        sa.Column("individual_contact_id", sa.Integer(), nullable=True),
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["individual_contact_id"],
            ["individual_contact.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "service_feedback_search_vector_idx",
        "service_feedback",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "service_feedback_search_vector_idx", table_name="service_feedback", postgresql_using="gin"
    )
    op.drop_table("service_feedback")
    # ### end Alembic commands ###
