"""Adds forms types

Revision ID: 99d317cbc848
Revises: f2605bfc1f59
Create Date: 2023-11-09 16:07:51.636218

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "99d317cbc848"
down_revision = "f2605bfc1f59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("forms_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("form_schema", sa.String(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["individual_contact.id"], ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "project_id")
    )
    op.create_index("forms_type_search_vector_idx", "forms_type", ["search_vector"], unique=False, postgresql_using="gin")
    op.create_table("forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_data", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("attorney_status", sa.String(), nullable=True),
        sa.Column("memo_link", sa.String(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("form_type_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["individual_contact.id"], ),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"], ),
        sa.ForeignKeyConstraint(["form_type_id"], ["forms_type.id"], ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("forms_search_vector_idx", "forms", ["search_vector"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("forms_type_search_vector_idx", table_name="forms_type", postgresql_using="gin")
    op.drop_table("forms_type")
    op.drop_index("forms_search_vector_idx", table_name="forms_type", postgresql_using="gin")
    op.drop_table("forms")
    # ### end Alembic commands ###
