"""Adds type to events

Revision ID: 3538650dc471
Revises: e875e9544048
Create Date: 2023-09-12 13:43:42.539336

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3538650dc471"
down_revision = "e875e9544048"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("type", sa.String(), nullable=True))
    op.add_column("event", sa.Column("owner", sa.String(), nullable=True))
    op.add_column("event", sa.Column("pinned", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "type")
    op.drop_column("event", "pinned")
    op.drop_column("event", "owner")
    # ### end Alembic commands ###
