"""Adds the ability to toggle signal definitions.

Revision ID: 5955ed5f76b4
Revises: 20d3801ad5b7
Create Date: 2023-03-02 11:12:18.168787

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5955ed5f76b4"
down_revision = "20d3801ad5b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signal", sa.Column("enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signal", "enabled")
    # ### end Alembic commands ###
