"""Adds case resolution reason

Revision ID: ec78c132ab93
Revises: 1d21b28bc553
Create Date: 2023-03-09 10:16:54.885960

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ec78c132ab93"
down_revision = "1d21b28bc553"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("resolution_reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case", "resolution_reason")
    # ### end Alembic commands ###
