"""empty message

Revision ID: 34584a8d60f6
Revises: 0a19c5a4c2ba
Create Date: 2023-06-26 09:35:45.666954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34584a8d60f6'
down_revision = '0a19c5a4c2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_priority', sa.Column('original_priority', sa.String(), nullable=True))
    op.add_column('case_priority', sa.Column('original_priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_priority', 'original_priority')
    op.drop_column('case_priority', 'original_priority')
    # ### end Alembic commands ###
