"""empty message

Revision ID: b48b245f9c4c
Revises: 7db13bf5c5d7
Create Date: 2023-03-14 16:56:11.844768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b48b245f9c4c"
down_revision = "7db13bf5c5d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assoc_signal_workflows",
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["signal_id"], ["signal.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflow.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("signal_id", "workflow_id"),
    )
    op.create_table(
        "assoc_signal_instance_tags",
        sa.Column("signal_instance_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["signal_instance_id"], ["signal_instance.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("signal_instance_id", "tag_id"),
    )
    op.drop_table("service_incident")
    op.drop_index("ix_entity_search_vector", table_name="entity")
    op.create_index(
        "entity_search_vector_idx",
        "entity",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("entity_search_vector_idx", table_name="entity", postgresql_using="gin")
    op.create_index("ix_entity_search_vector", "entity", ["search_vector"], unique=False)
    op.create_table(
        "service_incident",
        sa.Column("incident_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("service_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incident.id"], name="service_incident_incident_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["service.id"], name="service_incident_service_id_fkey"
        ),
        sa.PrimaryKeyConstraint("incident_id", "service_id", name="service_incident_pkey"),
    )
    op.drop_table("assoc_signal_instance_tags")
    op.drop_table("assoc_signal_workflows")
    # ### end Alembic commands ###
