"""Adds ondelete cascade to participant table for individual_contact FK

Revision ID: 1ded4c2a7801
Revises: 7ddae3ba7822
Create Date: 2023-03-08 10:18:03.250210

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ded4c2a7801"
down_revision = "7ddae3ba7822"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("participant_individual_contact_id_fkey", "participant", type_="foreignkey")
    op.create_foreign_key(
        None,
        "participant",
        "individual_contact",
        ["individual_contact_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.create_foreign_key(
        "participant_individual_contact_id_fkey",
        "participant",
        "individual_contact",
        ["individual_contact_id"],
        ["id"],
    )
    # ### end Alembic commands ###
