"""Adds new columns to the tag_type table to support new UI

Revision ID: 6c1a250b1e4b
Revises: 2f06fd73eae6
Create Date: 2023-12-18 10:22:13.668372

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6c1a250b1e4b"
down_revision = "2f06fd73eae6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag_type", sa.Column("discoverable", sa.Boolean(), nullable=True, server_default="t", default=True))
    op.add_column("tag_type", sa.Column("color", sa.String(), nullable=True))
    op.add_column("tag_type", sa.Column("icon", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag_type", "icon")
    op.drop_column("tag_type", "color")
    op.drop_column("tag_type", "discoverable")
    # ### end Alembic commands ###
