"""empty message

Revision ID: 956eb8f8987e
Revises: e23c468440c9
Create Date: 2023-01-27 11:11:47.149608

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "956eb8f8987e"
down_revision = "e23c468440c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant", sa.Column("user_conversation_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant", "user_conversation_id")
    # ### end Alembic commands ###
