"""Adds participants to the case model and introduces the observer role to cases.

Revision ID: 8d21322dc433
Revises: bd61c1e1e7cd
Create Date: 2023-01-03 13:48:51.288038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d21322dc433"
down_revision = "bd61c1e1e7cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("participants_team", sa.String(), nullable=True))
    op.add_column("case", sa.Column("participants_location", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "participant", "case", ["case_id"], ["id"], ondelete="CASCADE", use_alter=True
    )
    op.add_column("case", sa.Column("observer_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "case", "participant", ["observer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.drop_column("participant", "case_id")
    op.drop_column("case", "participants_location")
    op.drop_column("case", "participants_team")
    op.drop_constraint(None, "case", type_="foreignkey")
    op.drop_column("case", "observer_id")
    # ### end Alembic commands ###
