"""Adds reporter to Case model

Revision ID: fa23324d5679
Revises: 0a19c5a4c2ba
Create Date: 2023-07-03 11:12:32.679321

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fa23324d5679"
down_revision = "0a19c5a4c2ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("reporter_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "case", "participant", ["reporter_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "case", type_="foreignkey")
    op.drop_column("case", "reporter_id")
    # ### end Alembic commands ###
