"""Adds the engage_next_oncall column to the incident_role table.

Revision ID: 2f06fd73eae6
Revises: 580a18ec4c39
Create Date: 2023-12-08 11:22:15.565073

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2f06fd73eae6"
down_revision = "580a18ec4c39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_role", sa.Column("engage_next_oncall", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_role", "engage_next_oncall")
    # ### end Alembic commands ###
