"""Adds mfa_challenge to track challenges against core Dispatch MFA plugin.

Revision ID: 51eacaf1f62c
Revises: 71cd7ed999c4
Create Date: 2024-08-09 12:59:54.631968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51eacaf1f62c'
down_revision = 'd6b3853be8e4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_challenge',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('valid', sa.Boolean(), nullable=True, server_default=sa.text('true')),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('action', sa.String(), nullable=True),
        sa.Column('challenge_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('dispatch_user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['dispatch_user_id'], ['dispatch_core.dispatch_user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('challenge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mfa_challenge')
    # ### end Alembic commands ###
