"""Removes the cost_model field from Incident. Adds the cost_model field to IncidentType.
Revision ID: 50e99c66e72f
Revises: 3a33bc153e7e
Create Date: 2024-04-22 14:19:18.388675

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "50e99c66e72f"
down_revision = "3a33bc153e7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("incident_cost_model_id_fkey", "incident", type_="foreignkey")
    op.drop_column("incident", "cost_model_id")
    op.add_column("incident_type", sa.Column("cost_model_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "incident_type", "cost_model", ["cost_model_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incident_type", type_="foreignkey")
    op.drop_column("incident_type", "cost_model_id")
    op.add_column(
        "incident", sa.Column("cost_model_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "incident_cost_model_id_fkey", "incident", "cost_model", ["cost_model_id"], ["id"]
    )
    # ### end Alembic commands ###
