"""empty message

Revision ID: 50e99c66e72f
Revises: 3a33bc153e7e
Create Date: 2024-04-22 14:19:18.388675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50e99c66e72f'
down_revision = '3a33bc153e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assoc_signal_instance_tags',
    sa.Column('signal_instance_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signal_instance_id'], ['signal_instance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_instance_id', 'tag_id')
    )
    op.alter_column('entity', 'source',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_entity_search_vector', table_name='entity', postgresql_using='gin')
    op.create_index('entity_search_vector_idx', 'entity', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('entity_type', 'jpath',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('incident_cost_model_id_fkey', 'incident', type_='foreignkey')
    op.drop_column('incident', 'cost_model_id')
    op.add_column('incident_type', sa.Column('cost_model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incident_type', 'cost_model', ['cost_model_id'], ['id'])
    op.drop_column('plugin_instance', 'configuration')
    op.drop_constraint('project_stable_priority_id_fkey', 'project', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('project_stable_priority_id_fkey', 'project', 'incident_priority', ['stable_priority_id'], ['id'])
    op.add_column('plugin_instance', sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'incident_type', type_='foreignkey')
    op.drop_column('incident_type', 'cost_model_id')
    op.add_column('incident', sa.Column('cost_model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('incident_cost_model_id_fkey', 'incident', 'cost_model', ['cost_model_id'], ['id'])
    op.alter_column('entity_type', 'jpath',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('entity_search_vector_idx', table_name='entity', postgresql_using='gin')
    op.create_index('ix_entity_search_vector', 'entity', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('entity', 'source',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_table('assoc_signal_instance_tags')
    # ### end Alembic commands ###
