"""Adds email template table

Revision ID: 91bd05855ad1
Revises: 27e6558e26a8
Create Date: 2024-03-11 10:40:08.313520

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "91bd05855ad1"
down_revision = "27e6558e26a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_template_type", sa.String(), nullable=True),
        sa.Column("welcome_text", sa.String(), nullable=True),
        sa.Column("welcome_body", sa.String(), nullable=True),
        sa.Column("components", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_template_type", "project_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_templates")
    # ### end Alembic commands ###
