"""Adding display name to the projct model

Revision ID: 2d9e4d392ea4
Revises: 575ca7d954a8
Create Date: 2024-12-12 16:34:58.098426

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d9e4d392ea4"
down_revision = "575ca7d954a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("display_name", sa.String(), nullable=True))

    # Copy data from 'name' column to 'display_name' column
    op.execute("UPDATE project SET display_name = name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "display_name")
    # ### end Alembic commands ###
