"""Adds case_id to feedback

Revision ID: 3c49f62d7914
Revises: b8c1a8a4d957
Create Date: 2024-10-16 15:21:17.120891

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3c49f62d7914"
down_revision = "b8c1a8a4d957"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feedback", sa.Column("case_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "feedback", "case", ["case_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedback", type_="foreignkey")
    op.drop_column("feedback", "case_id")
    # ### end Alembic commands ###
