"""Adds lifecycle column to signal model

Revision ID: 71cd7ed999c4
Revises: ef17416626ff
Create Date: 2024-08-05 15:22:27.578399

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "71cd7ed999c4"
down_revision = "ef17416626ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signal", sa.Column("lifecycle", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signal", "lifecycle")
    # ### end Alembic commands ###
