"""Adds tickets to tasks and ticket metadata to incident types

Revision ID: b8c1a8a4d957
Revises: f5107ce190fc
Create Date: 2024-10-05 09:06:34.177407

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b8c1a8a4d957"
down_revision = "f5107ce190fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident_type",
        sa.Column("task_plugin_metadata", sa.JSON(), nullable=True, server_default="[]"),
    )
    op.add_column("ticket", sa.Column("task_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "ticket", "task", ["task_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ticket", type_="foreignkey")
    op.drop_column("ticket", "task_id")
    op.drop_column("incident_type", "task_plugin_metadata")
    # ### end Alembic commands ###
