"""Adds custom incident report card fields

Revision ID: f5107ce190fc
Revises: 1f4dc687945d
Create Date: 2024-09-27 12:33:17.418418

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f5107ce190fc"
down_revision = "1f4dc687945d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("report_incident_instructions", sa.String(), nullable=True))
    op.add_column("project", sa.Column("report_incident_title_hint", sa.String(), nullable=True))
    op.add_column(
        "project", sa.Column("report_incident_description_hint", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "report_incident_description_hint")
    op.drop_column("project", "report_incident_title_hint")
    op.drop_column("project", "report_incident_instructions")
    # ### end Alembic commands ###
