"""Creates a column for `dedicated_channel` on the Case model to support Cases
in dedicated coversation channel (as opposed to only threads).

Revision ID: 3a33bc153e7e
Revises: 71cb25c06fa0
Create Date: 2024-04-09 16:28:06.148971

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3a33bc153e7e"
down_revision = "71cb25c06fa0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("dedicated_channel", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case", "dedicated_channel")
    # ### end Alembic commands ###
