"""Allows association between documents and tags

Revision ID: ef17416626ff
Revises: a812a4cf61e1
Create Date: 2024-07-22 15:08:59.529688

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ef17416626ff"
down_revision = "a812a4cf61e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assoc_document_tags",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "tag_id"),
    )
    op.add_column("tag_type", sa.Column("discoverable_document", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag_type", "discoverable_document")
    op.drop_table("assoc_document_tags")
    # ### end Alembic commands ###
