"""Adds new genai prompt column to signal definition model

Revision ID: 1f4dc687945d
Revises: 19c10c121a22
Create Date: 2024-09-20 10:49:11.303112

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1f4dc687945d'
down_revision = '19c10c121a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal', sa.Column('genai_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal', 'genai_prompt')
    # ### end Alembic commands ###
