"""Adding display name to the projct model

Revision ID: 2d9e4d392ea4
Revises: 575ca7d954a8
Create Date: 2024-12-12 16:34:58.098426

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d9e4d392ea4"
down_revision = "575ca7d954a8"
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy import inspect
    from alembic import op
    import sqlalchemy as sa

    connection = op.get_bind()
    inspector = inspect(connection)
    schema = connection.dialect.default_schema_name

    print(f"Starting migration in schema: {schema}")
    print(f"Tables before migration: {inspector.get_table_names()}")
    print(f"Columns in 'project' table before migration: {[c['name'] for c in inspector.get_columns('project')]}")

    # Add the column
    print(f"Adding 'display_name' column to 'project' table in schema: {schema}")
    op.add_column(
        "project", sa.Column("display_name", sa.String(), server_default="", nullable=False)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "display_name")
    # ### end Alembic commands ###
