"""Adds genai_analysis to case model

Revision ID: b057c079c2d5
Revises: f5107ce190fc
Create Date: 2024-10-08 10:38:39.668625

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b057c079c2d5"
down_revision = "f5107ce190fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case",
        sa.Column(
            "genai_analysis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case", "genai_analysis")
    # ### end Alembic commands ###
