"""Adds restriction ability to incident severity

Revision ID: 0a6702319f6a
Revises: d6b3853be8e4
Create Date: 2024-09-10 10:13:04.192475

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0a6702319f6a"
down_revision = "d6b3853be8e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident_severity",
        sa.Column("allowed_for_stable_incidents", sa.Boolean(), server_default="t", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_severity", "allowed_for_stable_incidents")
    # ### end Alembic commands ###
