"""Adds project parameter to send weekly reports

Revision ID: f729d61738b0
Revises: 0a6702319f6a
Create Date: 2024-08-12 15:22:41.977924

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f729d61738b0"
down_revision = "0a6702319f6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "send_weekly_reports", sa.Boolean(), nullable=True, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "project", sa.Column("weekly_report_notification_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "send_weekly_reports")
    op.drop_column("project", "weekly_report_notification_id")
    # ### end Alembic commands ###
