"""Adds incident summary to the incident table.

Revision ID: 575ca7d954a8
Revises: 928b725d64f6
Create Date: 2024-12-05 15:05:46.932404

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "575ca7d954a8"
down_revision = "928b725d64f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident", sa.Column("summary", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident", "summary")
    # ### end Alembic commands ###
