"""Adding details column to support additional feedback information

Revision ID: 47d616802f56
Revises: 0a6702319f6a
Create Date: 2024-09-13 10:28:16.823990

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "47d616802f56"
down_revision = "0a6702319f6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_feedback", sa.Column("details", sa.JSON(), nullable=True))
    op.add_column("service_feedback_reminder", sa.Column("details", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_feedback_reminder", "details")
    op.drop_column("service_feedback", "details")
    # ### end Alembic commands ###
