"""Create new channel description and description service id columns for incident type

Revision ID: 4286dcce0a2d
Revises: a836d4850a75
Create Date: 2024-06-12 17:45:25.556120

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4286dcce0a2d"
down_revision = "a836d4850a75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_type", sa.Column("channel_description", sa.String(), nullable=True))
    op.add_column("incident_type", sa.Column("description_service_id", sa.Integer(), nullable=True))
    op.create_foreign_key("description_service_id_fkey", "incident_type", "service", ["description_service_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("description_service_id_fkey", "incident_type", type_="foreignkey")
    op.drop_column("incident_type", "description_service_id")
    op.drop_column("incident_type", "channel_description")
    # ### end Alembic commands ###
