"""Adds boolean column default to signal model

Revision ID: 0283f2bbe9dd
Revises: d4bbb234d0bc
Create Date: 2024-02-13 15:31:17.975089

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0283f2bbe9dd"
down_revision = "d4bbb234d0bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signal", sa.Column("default", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signal", "default")
    # ### end Alembic commands ###
