"""Add signal relationship to event

Revision ID: 8790ff1c8d6d
Revises: 753ea20c2680
Create Date: 2025-02-02 17:51:32.831061

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8790ff1c8d6d"
down_revision = "753ea20c2680"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("signal_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "event", "signal", ["signal_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event", type_="foreignkey")
    op.drop_column("event", "signal_id")
    # ### end Alembic commands ###
