"""empty message

Revision ID: 5f92be071aed
Revises: 4b3b62420a09
Create Date: 2025-06-23 11:27:02.743932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f92be071aed'
down_revision = '4b3b62420a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_snooze_extension_oncall_service_id_fkey', 'project', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('project_snooze_extension_oncall_service_id_fkey', 'project', 'service', ['snooze_extension_oncall_service_id'], ['id'])
    # ### end Alembic commands ###
