"""Add resolved_by to case table

Revision ID: 4649b11b683f
Revises: 408118048599
Create Date: 2025-08-01 14:11:04.276577

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4649b11b683f"
down_revision = "408118048599"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case", sa.Column("resolved_by_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_case_resolved_by_id", "case", "individual_contact", ["resolved_by_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_case_resolved_by_id", "case", type_="foreignkey")
    op.drop_column("case", "resolved_by_id")
    # ### end Alembic commands ###
