"""Adds column to exclude incident types from reminders

Revision ID: 2f18776252bb
Revises: 8790ff1c8d6d
Create Date: 2025-02-17 14:52:36.771074

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f18776252bb"
down_revision = "8790ff1c8d6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_type", sa.Column("exclude_from_reminders", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_type", "exclude_from_reminders")
    # ### end Alembic commands ###
