"""Adds disable delayed message warning column to case_priority table

Revision ID: 6e66b6578810
Revises: aa87efd3d6c1
Create Date: 2025-07-11 12:26:16.155438

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e66b6578810"
down_revision = "aa87efd3d6c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_priority", sa.Column("disable_delayed_message_warning", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case_priority", "disable_delayed_message_warning")
    # ### end Alembic commands ###
