"""Add GenAI suggestions column to tag_type table

Revision ID: 7fc3888c7b9a
Revises: 8f324b0f365a
Create Date: 2025-06-04 14:49:20.592746

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7fc3888c7b9a"
down_revision = "8f324b0f365a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag_type", sa.Column("genai_suggestions", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag_type", "genai_suggestions")
    # ### end Alembic commands ###
