"""Adds a column allowing an incident priority level configurable on whether a "IC will be slow to respond" Slack message

Revision ID: 753ea20c2680
Revises: dfc8e213a2c4
Create Date: 2025-01-24 13:48:26.599465

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "753ea20c2680"
down_revision = "dfc8e213a2c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident_priority",
        sa.Column("disable_delayed_message_warning", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_priority", "disable_delayed_message_warning")
    # ### end Alembic commands ###
