"""Adds column to exclude incident types from review

Revision ID: 92a359040b8e
Revises: 37406cca756c
Create Date: 2025-03-14 14:05:30.522240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a359040b8e'
down_revision = '37406cca756c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_type', sa.Column('exclude_from_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_type', 'exclude_from_review')
    # ### end Alembic commands ###
