"""Create canvas table.

Revision ID: ff08d822ef2c
Revises: f2bce475e71b
Create Date: 2025-08-28 15:33:37.139043

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ff08d822ef2c"
down_revision = "f2bce475e71b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canvas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canvas_id", sa.String(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["case.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("canvas")
    # ### end Alembic commands ###
