"""Add case notes model

Revision ID: df10accae9a9
Revises: f63ad392dbbf
Create Date: 2025-07-11 12:59:07.633861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df10accae9a9'
down_revision = 'f63ad392dbbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_notes', sa.Column('last_updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'case_notes', 'individual_contact', ['last_updated_by_id'], ['id'])
    op.drop_column('case_notes', 'last_updated_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_notes', sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'case_notes', type_='foreignkey')
    op.drop_column('case_notes', 'last_updated_by')
    # ### end Alembic commands ###
