"""Adds organization columns

Revision ID: 60c563588a03
Revises: f011c050b9ba
Create Date: 2021-06-08 11:41:09.749245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60c563588a03"
down_revision = "f011c050b9ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "dispatch_user_organization",
        "organization",
        ["organization_id"],
        ["id"],
        source_schema="dispatch_core",
        referent_schema="dispatch_core",
    )
    op.create_foreign_key(
        None,
        "dispatch_user_organization",
        "dispatch_user",
        ["dispatch_user_id"],
        ["id"],
        source_schema="dispatch_core",
        referent_schema="dispatch_core",
    )
    op.add_column("organization", sa.Column("banner_enabled", sa.Boolean(), nullable=True))
    op.add_column("organization", sa.Column("banner_color", sa.String(), nullable=True))
    op.add_column("organization", sa.Column("banner_text", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "banner_text")
    op.drop_column("organization", "banner_color")
    op.drop_column("organization", "banner_enabled")
    op.drop_constraint(
        None, "dispatch_user_organization", schema="dispatch_core", type_="foreignkey"
    )
    op.drop_constraint(
        None, "dispatch_user_organization", schema="dispatch_core", type_="foreignkey"
    )
    # ### end Alembic commands ###
