"""Adds last_mfa_time to DispatchUser

Revision ID: 3dd4d12844dc
Revises: e0d568f345c9
Create Date: 2023-04-14 15:17:00.450716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3dd4d12844dc"
down_revision = "e0d568f345c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dispatch_user", sa.Column("last_mfa_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dispatch_user", "last_mfa_time")
    # ### end Alembic commands ###
