"""empty message

Revision ID: 83ec59cd3e4c
Revises: ed0b0388fa3f
Create Date: 2024-04-22 14:19:17.541843

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '83ec59cd3e4c'
down_revision = 'ed0b0388fa3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dispatch_user_organization_organization_id_fkey', 'dispatch_user_organization', type_='foreignkey')
    op.drop_constraint('dispatch_user_organization_dispatch_user_id_fkey', 'dispatch_user_organization', type_='foreignkey')
    op.create_foreign_key(None, 'dispatch_user_organization', 'organization', ['organization_id'], ['id'], source_schema='dispatch_core', referent_schema='dispatch_core')
    op.create_foreign_key(None, 'dispatch_user_organization', 'dispatch_user', ['dispatch_user_id'], ['id'], source_schema='dispatch_core', referent_schema='dispatch_core')
    op.drop_constraint('plugin_event_plugin_id_fkey', 'plugin_event', type_='foreignkey')
    op.create_foreign_key(None, 'plugin_event', 'plugin', ['plugin_id'], ['id'], source_schema='dispatch_core', referent_schema='dispatch_core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plugin_event', schema='dispatch_core', type_='foreignkey')
    op.create_foreign_key('plugin_event_plugin_id_fkey', 'plugin_event', 'plugin', ['plugin_id'], ['id'])
    op.drop_constraint(None, 'dispatch_user_organization', schema='dispatch_core', type_='foreignkey')
    op.drop_constraint(None, 'dispatch_user_organization', schema='dispatch_core', type_='foreignkey')
    op.create_foreign_key('dispatch_user_organization_dispatch_user_id_fkey', 'dispatch_user_organization', 'dispatch_user', ['dispatch_user_id'], ['id'])
    op.create_foreign_key('dispatch_user_organization_organization_id_fkey', 'dispatch_user_organization', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###
