"""Add dispatch_user_settings table

Revision ID: 903183fd9aee
Revises: ed0b0388fa3f
Create Date: 2025-06-23 11:27:01.615306

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "903183fd9aee"
down_revision = "ed0b0388fa3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "dispatch_user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dispatch_user_id", sa.Integer(), nullable=True),
        sa.Column("auto_add_to_incident_bridges", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dispatch_user_id"],
            ["dispatch_core.dispatch_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dispatch_user_id"),
        schema="dispatch_core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dispatch_user_settings", schema="dispatch_core")
    # ### end Alembic commands ###
