"""Add data model for notifications

Revision ID: 0041b5414470
Revises: 996dea17749b
Create Date: 2021-01-20 12:49:32.313871

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "0041b5414470"
down_revision = "996dea17749b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_search_vector",
        "notification",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "notification_incident_priority",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("incident_priority_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_priority_id"], ["incident_priority.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_id", "incident_priority_id"),
    )
    op.create_table(
        "notification_incident_type",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("incident_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["incident_type_id"], ["incident_type.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_id", "incident_type_id"),
    )
    op.create_table(
        "notification_tag",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_id", "tag_id"),
    )
    op.create_table(
        "notification_term",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["term_id"], ["term.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_id", "term_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_term")
    op.drop_table("notification_tag")
    op.drop_table("notification_incident_type")
    op.drop_table("notification_incident_priority")
    op.drop_index("ix_notification_search_vector", table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
