"""Allows for multiple notification filters

Revision ID: 03f742366750
Revises: 57b1d2ee5a06
Create Date: 2021-01-22 14:25:11.322722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03f742366750"
down_revision = "57b1d2ee5a06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assoc_notification_filters",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("search_filter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["search_filter_id"], ["search_filter.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_id", "search_filter_id"),
    )
    op.drop_constraint("notification_search_filter_id_fkey", "notification", type_="foreignkey")
    op.drop_column("notification", "search_filter_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column("search_filter_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "notification_search_filter_id_fkey",
        "notification",
        "search_filter",
        ["search_filter_id"],
        ["id"],
    )
    op.drop_table("assoc_notification_filters")
    # ### end Alembic commands ###
