"""Adds a service description.

Revision ID: 057604415f6c
Revises: 343bc4e6aa79
Create Date: 2020-04-10 19:38:44.027653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "057604415f6c"
down_revision = "343bc4e6aa79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "description")
    # ### end Alembic commands ###
