"""Adds discoverable column

Revision ID: 1221a4d60f03
Revises: 14d7a4703d7c
Create Date: 2020-04-17 15:25:36.075381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from dispatch.tag.models import Tag


# revision identifiers, used by Alembic.
revision = "1221a4d60f03"
down_revision = "14d7a4703d7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("discoverable", sa.Boolean()))

    conn = op.get_bind()
    session = Session(bind=conn)

    for tag in session.query(Tag).all():
        tag.discoverable = True
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag", "discoverable")
    # ### end Alembic commands ###
