"""Adding a run reason.

Revision ID: 189759c2b5bf
Revises: 99f3dec93615
Create Date: 2020-10-01 14:53:31.791427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "189759c2b5bf"
down_revision = "99f3dec93615"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_instance", sa.Column("run_reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_instance", "run_reason")
    # ### end Alembic commands ###
