"""Adds liaison service mapping

Revision ID: 1c3f808aa00c
Revises: c6db1c7655db
Create Date: 2020-11-10 11:53:31.683415

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1c3f808aa00c"
down_revision = "c6db1c7655db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_type", sa.Column("liaison_service_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "incident_type", "service", ["liaison_service_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incident_type", type_="foreignkey")
    op.drop_column("incident_type", "liaison_service_id")
    # ### end Alembic commands ###
