"""Removes unnecessary columns and adds a colum to track if participant has been removed explicitly

Revision ID: 39264c4fe955
Revises: b3bf2da9be17
Create Date: 2021-05-11 17:30:13.671110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39264c4fe955"
down_revision = "b3bf2da9be17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant", sa.Column("removed_explicitly", sa.Boolean(), nullable=True))
    op.drop_column("participant", "is_active")
    op.drop_column("participant", "active_at")
    op.drop_column("participant", "inactive_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant",
        sa.Column("inactive_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "participant",
        sa.Column("active_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "participant", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_column("participant", "removed_explicitly")
    # ### end Alembic commands ###
