"""Adds additional fields to incident_type model.

Revision ID: 4691fc21e309
Revises: e3d9f5ca6958
Create Date: 2020-01-30 14:56:28.797631

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "4691fc21e309"
down_revision = "e3d9f5ca6958"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_type", sa.Column("commander_service_id", sa.Integer(), nullable=True))
    op.add_column(
        "incident_type",
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    )
    op.add_column("incident_type", sa.Column("slug", sa.String(), nullable=True))
    op.add_column("incident_type", sa.Column("template_document_id", sa.Integer(), nullable=True))
    op.create_index(
        "ix_incident_type_search_vector",
        "incident_type",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_foreign_key(None, "incident_type", "service", ["commander_service_id"], ["id"])
    op.create_foreign_key(None, "incident_type", "document", ["template_document_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incident_type", type_="foreignkey")
    op.drop_constraint(None, "incident_type", type_="foreignkey")
    op.drop_index("ix_incident_type_search_vector", table_name="incident_type")
    op.drop_column("incident_type", "template_document_id")
    op.drop_column("incident_type", "slug")
    op.drop_column("incident_type", "search_vector")
    op.drop_column("incident_type", "commander_service_id")
    # ### end Alembic commands ###
