"""Removes required column from plugins.

Revision ID: 48481a5575c1
Revises: efe949b0fe55
Create Date: 2021-05-06 15:28:31.228556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48481a5575c1"
down_revision = "efe949b0fe55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plugin", "required")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugin", sa.Column("required", sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
