"""Adds visibility column to incident_type model

Revision ID: 50d0688878ae
Revises: 4691fc21e309
Create Date: 2020-03-17 15:07:08.261027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50d0688878ae"
down_revision = "4691fc21e309"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_type", sa.Column("visibility", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_type", "visibility")
    # ### end Alembic commands ###
