"""Adds enabled columns

Revision ID: 52f89b68cd84
Revises: 48481a5575c1
Create Date: 2021-05-06 16:01:29.933578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52f89b68cd84"
down_revision = "48481a5575c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_priority", sa.Column("enabled", sa.Boolean(), nullable=True))
    op.execute("update incident_priority set enabled = true")
    op.add_column("incident_type", sa.Column("enabled", sa.Boolean(), nullable=True))
    op.execute("update incident_type set enabled = true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_type", "enabled")
    op.drop_column("incident_priority", "enabled")
    # ### end Alembic commands ###
