"""Adds banner info to organization

Revision ID: 58066ecf68c5
Revises: 47d04a78a9e4
Create Date: 2021-05-23 12:43:56.928793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58066ecf68c5"
down_revision = "47d04a78a9e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("banner_color", sa.String(), nullable=True))
    op.add_column("organization", sa.Column("banner_enabled", sa.Boolean(), nullable=True))
    op.add_column("organization", sa.Column("banner_text", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "banner_text")
    op.drop_column("organization", "banner_enabled")
    op.drop_column("organization", "banner_color")
    # ### end Alembic commands ###
