"""empty message

Revision ID: 60d6d32f7027
Revises: 69ac7f6dc0da
Create Date: 2020-08-13 09:54:27.538474

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "60d6d32f7027"
down_revision = "69ac7f6dc0da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("details", sqlalchemy_utils.types.json.JSONType(), nullable=True),
        sa.Column("details_raw", sa.String(), nullable=True),
        sa.Column("type", sa.String(), server_default="Tactical Report", nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"],),
        sa.ForeignKeyConstraint(["participant_id"], ["participant.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_report_search_vector", "report", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "task_tickets",
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"],),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.id"],),
        sa.PrimaryKeyConstraint("ticket_id", "task_id"),
    )
    op.drop_table("status_report")
    op.create_foreign_key(None, "document", "report", ["report_id"], ["id"])
    op.add_column(
        "incident_priority",
        sa.Column("executive_report_reminder", sa.Integer(), server_default="24", nullable=True),
    )
    op.add_column(
        "incident_priority",
        sa.Column("tactical_report_reminder", sa.Integer(), server_default="24", nullable=True),
    )
    op.drop_column("incident_priority", "status_reminder")
    op.alter_column(
        "incident_type",
        "plugin_metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::json"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "incident_type",
        "plugin_metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.add_column(
        "incident_priority",
        sa.Column("status_reminder", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("incident_priority", "tactical_report_reminder")
    op.drop_column("incident_priority", "executive_report_reminder")
    op.drop_constraint(None, "document", type_="foreignkey")
    op.create_table(
        "status_report",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("conditions", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("actions", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("needs", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("incident_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("participant_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incident.id"], name="status_report_incident_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"], ["participant.id"], name="status_report_participant_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="status_report_pkey"),
    )
    op.drop_table("task_tickets")
    op.drop_index("ix_report_search_vector", table_name="report")
    op.drop_table("report")
    # ### end Alembic commands ###
