"""empty message

Revision ID: 72c7fa0ce0a3
Revises: 466823f3046e
Create Date: 2020-09-24 10:00:34.338853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c7fa0ce0a3'
down_revision = '466823f3046e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('plugin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflow', 'plugin', ['plugin_id'], ['id'])
    op.drop_column('workflow', 'plugin_slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('plugin_slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'plugin_id')
    # ### end Alembic commands ###
