"""Adds missing workflow cascades

Revision ID: 7c98af096101
Revises: 6dba21b862d6
Create Date: 2021-03-18 09:16:00.699130

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c98af096101"
down_revision = "6dba21b862d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "workflow_incident_priority_workflow_id_fkey",
        "workflow_incident_priority",
        type_="foreignkey",
    )
    op.drop_constraint(
        "workflow_incident_priority_incident_priority_id_fkey",
        "workflow_incident_priority",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "workflow_incident_priority",
        "incident_priority",
        ["incident_priority_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "workflow_incident_priority", "workflow", ["workflow_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "workflow_incident_type_incident_type_id_fkey", "workflow_incident_type", type_="foreignkey"
    )
    op.drop_constraint(
        "workflow_incident_type_workflow_id_fkey", "workflow_incident_type", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "workflow_incident_type",
        "incident_type",
        ["incident_type_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "workflow_incident_type", "workflow", ["workflow_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("workflow_term_term_id_fkey", "workflow_term", type_="foreignkey")
    op.drop_constraint("workflow_term_workflow_id_fkey", "workflow_term", type_="foreignkey")
    op.create_foreign_key(None, "workflow_term", "term", ["term_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "workflow_term", "workflow", ["workflow_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow_term", type_="foreignkey")
    op.drop_constraint(None, "workflow_term", type_="foreignkey")
    op.create_foreign_key(
        "workflow_term_workflow_id_fkey", "workflow_term", "workflow", ["workflow_id"], ["id"]
    )
    op.create_foreign_key(
        "workflow_term_term_id_fkey", "workflow_term", "term", ["term_id"], ["id"]
    )
    op.drop_constraint(None, "workflow_incident_type", type_="foreignkey")
    op.drop_constraint(None, "workflow_incident_type", type_="foreignkey")
    op.create_foreign_key(
        "workflow_incident_type_workflow_id_fkey",
        "workflow_incident_type",
        "workflow",
        ["workflow_id"],
        ["id"],
    )
    op.create_foreign_key(
        "workflow_incident_type_incident_type_id_fkey",
        "workflow_incident_type",
        "incident_type",
        ["incident_type_id"],
        ["id"],
    )
    op.drop_constraint(None, "workflow_incident_priority", type_="foreignkey")
    op.drop_constraint(None, "workflow_incident_priority", type_="foreignkey")
    op.create_foreign_key(
        "workflow_incident_priority_incident_priority_id_fkey",
        "workflow_incident_priority",
        "incident_priority",
        ["incident_priority_id"],
        ["id"],
    )
    op.create_foreign_key(
        "workflow_incident_priority_workflow_id_fkey",
        "workflow_incident_priority",
        "workflow",
        ["workflow_id"],
        ["id"],
    )
    # ### end Alembic commands ###
