"""Adds the notification data model

Revision ID: 88b7c4f7ac0f
Revises: 996dea17749b
Create Date: 2021-01-15 12:07:30.772992

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "88b7c4f7ac0f"
down_revision = "996dea17749b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_name", sa.String(), nullable=True),
        sa.Column("conversation_description", sa.String(), nullable=True),
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_search_vector",
        "notification",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "notification_incident_priority",
        sa.Column("incident_priority_id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_priority_id"], ["incident_priority.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("incident_priority_id", "notification_id"),
    )
    op.create_table(
        "notification_incident_type",
        sa.Column("incident_type_id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["incident_type_id"], ["incident_type.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("incident_type_id", "notification_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_incident_type")
    op.drop_table("notification_incident_priority")
    op.drop_index("ix_notification_search_vector", table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
