"""empty message

Revision ID: 8b67c774279d
Revises: e7c696ffd69a
Create Date: 2020-03-24 14:08:47.756920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b67c774279d'
down_revision = 'e7c696ffd69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assoc_incident_tags',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'tag_id')
    )
    op.drop_table('tags_incidents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_incidents',
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name='tags_incidents_incident_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='tags_incidents_tag_id_fkey'),
    sa.PrimaryKeyConstraint('incident_id', 'tag_id', name='tags_incidents_pkey')
    )
    op.drop_table('assoc_incident_tags')
    # ### end Alembic commands ###
