"""Adds unique constraint to the service model

Revision ID: 90ddc69b8300
Revises: 87400096f4cc
Create Date: 2021-04-27 15:37:48.611654

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "90ddc69b8300"
down_revision = "87400096f4cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "service", ["external_id", "project_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service", type_="unique")
    # ### end Alembic commands ###
