"""Adds ondelete cascade to task_assignees and task_tickets assoc tables

Revision ID: 996dea17749b
Revises: 38f0b01448ba
Create Date: 2021-01-12 10:36:53.281512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "996dea17749b"
down_revision = "38f0b01448ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_assignees_task_id_fkey", "task_assignees", type_="foreignkey")
    op.drop_constraint("task_assignees_participant_id_fkey", "task_assignees", type_="foreignkey")
    op.create_foreign_key(None, "task_assignees", "task", ["task_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "task_assignees", "participant", ["participant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("task_tickets_task_id_fkey", "task_tickets", type_="foreignkey")
    op.drop_constraint("task_tickets_ticket_id_fkey", "task_tickets", type_="foreignkey")
    op.create_foreign_key(None, "task_tickets", "task", ["task_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "task_tickets", "ticket", ["ticket_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_tickets", type_="foreignkey")
    op.drop_constraint(None, "task_tickets", type_="foreignkey")
    op.create_foreign_key(
        "task_tickets_ticket_id_fkey", "task_tickets", "ticket", ["ticket_id"], ["id"]
    )
    op.create_foreign_key("task_tickets_task_id_fkey", "task_tickets", "task", ["task_id"], ["id"])
    op.drop_constraint(None, "task_assignees", type_="foreignkey")
    op.drop_constraint(None, "task_assignees", type_="foreignkey")
    op.create_foreign_key(
        "task_assignees_participant_id_fkey",
        "task_assignees",
        "participant",
        ["participant_id"],
        ["id"],
    )
    op.create_foreign_key(
        "task_assignees_task_id_fkey", "task_assignees", "task", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
