"""Adds priorities, terms, types, and artifact relationships and tables.

Revision ID: 99f3dec93615
Revises: 9f927a8e4679
Create Date: 2020-09-28 15:47:08.865362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f3dec93615'
down_revision = '9f927a8e4679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_incident_priority',
    sa.Column('incident_priority_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_priority_id'], ['incident_priority.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('incident_priority_id', 'workflow_id')
    )
    op.create_table('workflow_incident_type',
    sa.Column('incident_type_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_type.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('incident_type_id', 'workflow_id')
    )
    op.create_table('workflow_term',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('term_id', 'workflow_id')
    )
    op.create_table('workflow_instance_artifact',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('workflow_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'workflow_instance_id')
    )
    op.drop_table('workflow_instance_artifacts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_instance_artifacts',
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_instance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='workflow_instance_artifacts_document_id_fkey'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], name='workflow_instance_artifacts_workflow_instance_id_fkey'),
    sa.PrimaryKeyConstraint('document_id', 'workflow_instance_id', name='workflow_instance_artifacts_pkey')
    )
    op.drop_table('workflow_instance_artifact')
    op.drop_table('workflow_term')
    op.drop_table('workflow_incident_type')
    op.drop_table('workflow_incident_priority')
    # ### end Alembic commands ###
