"""Adds an organization column to participants

Revision ID: 9b26060dc0bc
Revises: 69ac7f6dc0da
Create Date: 2020-07-14 16:06:14.128672

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "9b26060dc0bc"
down_revision = "69ac7f6dc0da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant",
        sa.Column("organization", sqlalchemy_utils.types.ltree.LtreeType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant", "organization")
    # ### end Alembic commands ###
