"""Adds an external ID column to individual model.

Revision ID: a769ea6bad64
Revises: 7c98af096101
Create Date: 2021-03-18 10:06:20.030586

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a769ea6bad64"
down_revision = "7c98af096101"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("individual_contact", sa.Column("external_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("individual_contact", "external_id")
    # ### end Alembic commands ###
