"""Enables user emails to be searchable.

Revision ID: ab9879051d6c
Revises: e2bdb8fb6dfe
Create Date: 2020-07-06 10:43:12.196383

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "ab9879051d6c"
down_revision = "e2bdb8fb6dfe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dispatch_user",
        sa.Column("search_vector", sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    )
    op.create_index(
        "ix_dispatch_user_search_vector",
        "dispatch_user",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dispatch_user_search_vector", table_name="dispatch_user")
    op.drop_column("dispatch_user", "search_vector")
    # ### end Alembic commands ###
