"""empty message

Revision ID: ac72944abe8f
Revises: a32bfbb4bcaa
Create Date: 2020-05-18 19:30:40.777458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac72944abe8f'
down_revision = 'a32bfbb4bcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_type', sa.Column('plugin_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_type', 'plugin_metadata')
    # ### end Alembic commands ###
