"""Adds conference data model

Revision ID: b12f7a59ced9
Revises: 81038e961414
Create Date: 2020-03-20 09:05:21.184011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b12f7a59ced9"
down_revision = "81038e961414"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conference",
        sa.Column("resource_type", sa.String(), nullable=True),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("weblink", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conference_id", sa.String(), nullable=True),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conference")
    # ### end Alembic commands ###
