"""Adds role fields to user for use with RBAC permissions.

Revision ID: b174201e181b
Revises: 2d3e511db6b4
Create Date: 2020-04-24 15:33:16.370022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b174201e181b"
down_revision = "2d3e511db6b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dispatch_user", sa.Column("role", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dispatch_user", "role")
    # ### end Alembic commands ###
