"""Adds color column to projects

Revision ID: b3bf2da9be17
Revises: 52f89b68cd84
Create Date: 2021-05-07 09:28:25.055939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3bf2da9be17"
down_revision = "52f89b68cd84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "color")
    # ### end Alembic commands ###
