"""Adds column for FAIR form of loss category

Revision ID: b6da2dad0396
Revises: a769ea6bad64
Create Date: 2021-03-19 13:07:36.153462

"""
from alembic import op
import sqlalchemy as sa

from dispatch.database.base import SessionLocal
from dispatch.incident_cost_type.models import IncidentCostTypeUpdate
from dispatch.incident_cost_type import service as incident_cost_type_service


# revision identifiers, used by Alembic.
revision = "b6da2dad0396"
down_revision = "a769ea6bad64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_cost_type", sa.Column("category", sa.String(), nullable=True))

    # we set the category of the default response incident cost type
    db_session = SessionLocal()
    incident_cost_type = incident_cost_type_service.get_default(db_session=db_session)
    if incident_cost_type:
        incident_cost_type_in = IncidentCostTypeUpdate(
            id=incident_cost_type.id, name=incident_cost_type.name, category="Primary"
        )
        incident_cost_type_service.update(
            db_session=db_session,
            incident_cost_type=incident_cost_type,
            incident_cost_type_in=incident_cost_type_in,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_cost_type", "category")
    # ### end Alembic commands ###
