"""empty message

Revision ID: cfd62f719c84
Revises: 5693756fd192
Create Date: 2020-05-26 20:17:47.707953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cfd62f719c84"
down_revision = "5693756fd192"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_type", "plugin_metadata")
    op.add_column("incident_type", sa.Column("plugin_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
