"""Adds status report reminder.

Revision ID: d841f9945338
Revises: 5957303b1b8a
Create Date: 2020-04-02 15:41:18.924506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd841f9945338'
down_revision = '5957303b1b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_priority', sa.Column('status_reminder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_priority', 'status_reminder')
    # ### end Alembic commands ###
