"""Adds the ability to specify a task owner.

Revision ID: ecdb4e7566f2
Revises: 69ac7f6dc0da
Create Date: 2020-07-29 14:04:30.358195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ecdb4e7566f2"
down_revision = "69ac7f6dc0da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "task", "participant", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "owner_id")
    # ### end Alembic commands ###
