name: Test image build

on: pull_request

jobs:
  build_image:
    name: Build Docker image
    runs-on: bp-ubuntu-latest-x64-4x
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build without push
        uses: docker/build-push-action@v1
        with:
          push: false
