name: Python Lint and Test

on: pull_request

jobs:
  test:
    env:
      # Minimum code coverage per file
      COVERAGE_SINGLE: 10
      # Minimum total code coverage
      COVERAGE_TOTAL: 40
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dispatch
          POSTGRES_DB: dispatch
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install python dependencies
        run: |
          export DISPATCH_LIGHT_BUILD=1
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: "Lint with ruff"
        run: |
          ruff check src tests
          ruff format src tests
      - name: Test with pytest
        run: |
          pip install pytest-cov
          pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: pytester-cov
        id: pytester-cov
        uses: programmingwithalex/pytester-cov@main
        with:
          pytest-root-dir: '.'
          cov-omit-list: 'src/dispatch/*/views.py, src/dispatch/*/scheduled.py, src/dispatch/rate_limiter.py, src/dispatch/plugins/dispatch_test/*, src/dispatch/api.py, src/dispatch/extensions.py, src/dispatch/scheduler.py'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
      - name: Coverage single fail - exit
        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
        run: |
          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
          # exit 1
      - name: Coverage total fail - exit
        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
        run: |
          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
          # exit 1
