name: Python Lint and Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dispatch
          POSTGRES_DB: dispatch
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          export DISPATCH_LIGHT_BUILD=1
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run Black
        run: |
          black .

      - name: Run Flake8
        run: |
          flake8 .

      - name: Test with pytest
        run: |
          pytest
