name: 'Close stale issues and pull requests'
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale, because it has been open for 30 days with no activity. Remove the stale label or comment, or this will be closed in 5 days.'
        close-issue-message: 'This issue was closed, because it has been stalled for 5 days with no activity.'
        stale-pr-message: 'This PR is stale, because it has been open for 45 days with no activity. Remove the stale label or comment, or this will be closed in 10 days.'
        close-pr-message: 'This PR was closed, because it has been stalled for 10 days with no activity.'
        days-before-issue-stale: 30
        days-before-issue-close: 5
        days-before-pr-stale: 45
        days-before-pr-close: 10
